#pragma once

#include <ve_driver_api.h>

extern "C" {
// DataTypes -------------------------------------------------------------------
struct VEblas;
typedef VEblas* veblasHandle_t;

struct float2 {
	float x, y;
};

struct double2 {
	double x, y;
};

typedef struct float2 veFloatComplex_t;
typedef struct double2 veDoubleComplex_t;
typedef const char* veblasOperation_t;
typedef int veblasInt_t;

// Management Functions --------------------------------------------------------
//veblasStatus_t	veblasGetPointerMode(veblasHandle_t handle, veblasPointerMode_t* mode);
//veblasStatus_t	veblasSetPointerMode(veblasHandle_t handle, veblasPointerMode_t mode);
veblasStatus_t	veblasCreate		(veblasHandle_t* handle);
veblasStatus_t	veblasDestroy		(veblasHandle_t handle);
veblasStatus_t	veblasGetMatrix		(int rows, int cols, int elemSize, const void* A, int lda, void* B, int ldb);
veblasStatus_t	veblasGetMatrixAsync(int rows, int cols, int elemSize, const void* A, int lda, void* B, int ldb, VEDAstream stream);
veblasStatus_t	veblasGetStream		(veblasHandle_t handle, VEDAstream* streamId);
veblasStatus_t	veblasGetVector		(int n, int elemSize, const void* x, int incx, void* y, int incy);
veblasStatus_t	veblasGetVectorAsync(int n, int elemSize, const void* devicePtr, int incx, void* hostPtr, int incy, VEDAstream stream);
veblasStatus_t	veblasGetVersion	(veblasHandle_t handle, int* version);
veblasStatus_t	veblasSetMatrix		(int rows, int cols, int elemSize, const void* A, int lda, void* B, int ldb);
veblasStatus_t	veblasSetMatrixAsync(int rows, int cols, int elemSize, const void* A, int lda, void* B, int ldb, VEDAstream stream);
veblasStatus_t	veblasSetStream		(veblasHandle_t handle, VEDAstream streamId);
veblasStatus_t	veblasSetVector		(int n, int elemSize, const void* x, int incx, void* y, int incy);
veblasStatus_t	veblasSetVectorAsync(int n, int elemSize, const void* hostPtr, int incx, void* devicePtr, int incy, VEDAstream stream);

// Level-1 ---------------------------------------------------------------------
//veblasStatus_t	veblasCdotc	(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* result);
//veblasStatus_t	veblasCdotu	(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* result);
//veblasStatus_t	veblasCrot	(veblasHandle_t handle, int n, veFloatComplex_t* x, int incx, veFloatComplex_t* y, int incy, const float* c, const veFloatComplex_t* s);
//veblasStatus_t	veblasCrotg	(veblasHandle_t handle, veFloatComplex_t* a, veFloatComplex_t* b, float* c, veFloatComplex_t* s);
//veblasStatus_t	veblasCsrot	(veblasHandle_t handle, int n, veFloatComplex_t* x, int incx, veFloatComplex_t* y, int incy, const float* c, const float* s);
//veblasStatus_t	veblasIcamin(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, int* result);
//veblasStatus_t	veblasIdamin(veblasHandle_t handle, int n, const double* x, int incx, int* result);
//veblasStatus_t	veblasIsamin(veblasHandle_t handle, int n, const float* x, int incx, int* result);
//veblasStatus_t	veblasIzamin(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, int* result);
//veblasStatus_t	veblasZdotc	(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* result);
//veblasStatus_t	veblasZdotu	(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* result);
//veblasStatus_t	veblasZdrot	(veblasHandle_t handle, int n, veDoubleComplex_t* x, int incx, veDoubleComplex_t* y, int incy, const double* c, const double* s);
//veblasStatus_t	veblasZrot	(veblasHandle_t handle, int n, veDoubleComplex_t* x, int incx, veDoubleComplex_t* y, int incy, const double* c, const veDoubleComplex_t* s);
//veblasStatus_t	veblasZrotg	(veblasHandle_t handle, veDoubleComplex_t* a, veDoubleComplex_t* b, double* c, veDoubleComplex_t* s);
veblasStatus_t	veblasCaxpy	(veblasHandle_t handle, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasCcopy	(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasCscal	(veblasHandle_t handle, int n, const veFloatComplex_t* alpha, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCsscal(veblasHandle_t handle, int n, const float* alpha, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCswap	(veblasHandle_t handle, int n, veFloatComplex_t* x, int incx, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasDasum	(veblasHandle_t handle, int n, const double* x, int incx, double* result);
veblasStatus_t	veblasDaxpy	(veblasHandle_t handle, int n, const double* alpha, const double* x, int incx, double* y, int incy);
veblasStatus_t	veblasDcopy	(veblasHandle_t handle, int n, const double* x, int incx, double* y, int incy);
veblasStatus_t	veblasDdot 	(veblasHandle_t handle, int n, const double* x, int incx, const double* y, int incy, double* result);
veblasStatus_t	veblasDnrm2	(veblasHandle_t handle, int n, const double* x, int incx, double* result);
veblasStatus_t	veblasDrot	(veblasHandle_t handle, int n, double* x, int incx, double* y, int incy, const double* c, const double* s);
veblasStatus_t	veblasDrotg	(veblasHandle_t handle, double* a, double* b, double* c, double* s);
veblasStatus_t	veblasDrotm	(veblasHandle_t handle, int n, double* x, int incx, double* y, int incy, const double* param);
veblasStatus_t	veblasDscal	(veblasHandle_t handle, int n, const double* alpha, double* x, int incx);
veblasStatus_t	veblasDswap	(veblasHandle_t handle, int n, double* x, int incx, double* y, int incy);
veblasStatus_t	veblasDzasum(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, double* result);
veblasStatus_t	veblasDznrm2(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, double* result);
veblasStatus_t	veblasIcamax(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, int* result);
veblasStatus_t	veblasIdamax(veblasHandle_t handle, int n, const double* x, int incx, int* result);
veblasStatus_t	veblasIsamax(veblasHandle_t handle, int n, const float* x, int incx, int* result);
veblasStatus_t	veblasIzamax(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, int* result);
veblasStatus_t	veblasSasum	(veblasHandle_t handle, int n, const float* x, int incx, float* result);
veblasStatus_t	veblasSaxpy	(veblasHandle_t handle, int n, const float* alpha, const float* x, int incx, float* y, int incy);
veblasStatus_t	veblasScasum(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, float* result);
veblasStatus_t	veblasScnrm2(veblasHandle_t handle, int n, const veFloatComplex_t* x, int incx, float* result);
veblasStatus_t	veblasScopy	(veblasHandle_t handle, int n, const float* x, int incx, float* y, int incy);
veblasStatus_t	veblasSdot 	(veblasHandle_t handle, int n, const float* x, int incx, const float* y, int incy, float* result);
veblasStatus_t	veblasSnrm2	(veblasHandle_t handle, int n, const float* x, int incx, float* result);
veblasStatus_t	veblasSrot	(veblasHandle_t handle, int n, float* x, int incx, float* y, int incy, const float* c, const float* s);
veblasStatus_t	veblasSrotg	(veblasHandle_t handle, float* a, float* b, float* c, float* s);
veblasStatus_t	veblasSrotm	(veblasHandle_t handle, int n, float* x, int incx, float* y, int incy, const float* param);
veblasStatus_t	veblasSscal	(veblasHandle_t handle, int n, const float* alpha, float* x, int incx);
veblasStatus_t	veblasSswap	(veblasHandle_t handle, int n, float* x, int incx, float* y, int incy);
veblasStatus_t	veblasZaxpy	(veblasHandle_t handle, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZcopy	(veblasHandle_t handle, int n, const veDoubleComplex_t* x, int incx, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZdscal(veblasHandle_t handle, int n, const double* alpha, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZscal	(veblasHandle_t handle, int n, const veDoubleComplex_t* alpha, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZswap	(veblasHandle_t handle, int n, veDoubleComplex_t* x, int incx, veDoubleComplex_t* y, int incy);

// Level-2 ---------------------------------------------------------------------
//veblasStatus_t	veblasCsymv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
//veblasStatus_t	veblasCsyr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, veFloatComplex_t* A, int lda);
//veblasStatus_t	veblasCsyr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* A, int lda;
//veblasStatus_t	veblasZsymv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
//veblasStatus_t	veblasZsyr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, veDoubleComplex_t* A, int lda);
//veblasStatus_t	veblasZsyr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* A, int lda;
eblasStatus_t	veblasCgerc	(veblasHandle_t handle, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* A, int lda);
eblasStatus_t	veblasCgeru	(veblasHandle_t handle, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* A, int lda);
eblasStatus_t	veblasDger	(veblasHandle_t handle, int m, int n, const double* alpha, const double* x, int incx, const double* y, int incy, double* A, int lda);
eblasStatus_t	veblasSger	(veblasHandle_t handle, int m, int n, const float* alpha, const float* x, int incx, const float* y, int incy, float* A, int lda);
eblasStatus_t	veblasZgerc	(veblasHandle_t handle, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* A, int lda);
eblasStatus_t	veblasZgeru	(veblasHandle_t handle, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* A, int lda);
veblasStatus_t	veblasCgbmv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, int kl, int ku, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasCgemv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasChbmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasChemv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasCher	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const veFloatComplex_t* x, int incx, veFloatComplex_t* A, int lda);
veblasStatus_t	veblasCher2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* A, int lda);
veblasStatus_t	veblasChpmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* AP, const veFloatComplex_t* x, int incx, const veFloatComplex_t* beta, veFloatComplex_t* y, int incy);
veblasStatus_t	veblasChpr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const veFloatComplex_t* x, int incx, veFloatComplex_t* AP);
veblasStatus_t	veblasChpr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* x, int incx, const veFloatComplex_t* y, int incy, veFloatComplex_t* AP);
veblasStatus_t	veblasCtbmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const veFloatComplex_t* A, int lda, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCtbsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const veFloatComplex_t* A, int lda, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCtpmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veFloatComplex_t* AP, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCtpsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veFloatComplex_t* AP, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCtrmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veFloatComplex_t* A, int lda, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasCtrsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veFloatComplex_t* A, int lda, veFloatComplex_t* x, int incx);
veblasStatus_t	veblasDgbmv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, int kl, int ku, const double* alpha, const double* A, int lda, const double* x, int incx, const double* beta, double* y, int incy);
veblasStatus_t	veblasDgemv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, const double* alpha, const double* A, int lda, const double* x, int incx, const double* beta, double* y, int incy);
veblasStatus_t	veblasDsbmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, int k, const double* alpha, const double* A, int lda, const double* x, int incx, const double* beta, double* y, int incy);
veblasStatus_t	veblasDspmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* AP, const double* x, int incx, const double* beta, double* y, int incy);
veblasStatus_t	veblasDspr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* x, int incx, double* AP);
veblasStatus_t	veblasDspr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* x, int incx, const double* y, int incy, double* AP);
veblasStatus_t	veblasDsymv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* A, int lda, const double* x, int incx, const double* beta, double* y, int incy);
veblasStatus_t	veblasDsyr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* x, int incx, double* A, int lda);
veblasStatus_t	veblasDsyr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const double* x, int incx, const double* y, int incy, double* A, int lda;
veblasStatus_t	veblasDtbmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const double* A, int lda, double* x, int incx);
veblasStatus_t	veblasDtbsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const double* A, int lda, double* x, int incx);
veblasStatus_t	veblasDtpmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const double* AP, double* x, int incx);
veblasStatus_t	veblasDtpsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const double* AP, double* x, int incx);
veblasStatus_t	veblasDtrmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const double* A, int lda, double* x, int incx);
veblasStatus_t	veblasDtrsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const double* A, int lda, double* x, int incx);
veblasStatus_t	veblasSgbmv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, int kl, int ku, const float* alpha, const float* A, int lda, const float* x, int incx, const float* beta, float* y, int incy);
veblasStatus_t	veblasSgemv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, const float* alpha, const float* A, int lda, const float* x, int incx, const float* beta, float* y, int incy);
veblasStatus_t	veblasSsbmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, int k, const float* alpha, const float* A, int lda, const float* x, int incx, const float* beta, float* y, int incy);
veblasStatus_t	veblasSspmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* AP, const float* x, int incx, const float* beta, float* y, int incy);
veblasStatus_t	veblasSspr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* x, int incx, float* AP);
veblasStatus_t	veblasSspr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* x, int incx, const float* y, int incy, float* AP);
veblasStatus_t	veblasSsymv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* A, int lda, const float* x, int incx, const float* beta, float* y, int incy);
veblasStatus_t	veblasSsyr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* x, int incx, float* A, int lda);
veblasStatus_t	veblasSsyr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const float* alpha, const float* x, int incx, const float* y, int incy, float* A, int lda;
veblasStatus_t	veblasStbmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const float* A, int lda, float* x, int incx);
veblasStatus_t	veblasStbsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const float* A, int lda, float* x, int incx);
veblasStatus_t	veblasStpmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const float* AP, float* x, int incx);
veblasStatus_t	veblasStpsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const float* AP, float* x, int incx);
veblasStatus_t	veblasStrmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const float* A, int lda, float* x, int incx);
veblasStatus_t	veblasStrsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const float* A, int lda, float* x, int incx);
veblasStatus_t	veblasZgbmv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, int kl, int ku, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZgemv	(veblasHandle_t handle, veblasOperation_t trans, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZhbmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZhemv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZher	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const veDoubleComplex_t* x, int incx, veDoubleComplex_t* A, int lda);
veblasStatus_t	veblasZher2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* A, int lda);
veblasStatus_t	veblasZhpmv	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* AP, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* beta, veDoubleComplex_t* y, int incy);
veblasStatus_t	veblasZhpr	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const double* alpha, const veDoubleComplex_t* x, int incx, veDoubleComplex_t* AP);
veblasStatus_t	veblasZhpr2	(veblasHandle_t handle, veblasFillMode_t uplo, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* x, int incx, const veDoubleComplex_t* y, int incy, veDoubleComplex_t* AP);
veblasStatus_t	veblasZtbmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const veDoubleComplex_t* A, int lda, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZtbsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, int k, const veDoubleComplex_t* A, int lda, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZtpmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veDoubleComplex_t* AP, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZtpsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veDoubleComplex_t* AP, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZtrmv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veDoubleComplex_t* A, int lda, veDoubleComplex_t* x, int incx);
veblasStatus_t	veblasZtrsv	(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int n, const veDoubleComplex_t* A, int lda, veDoubleComplex_t* x, int incx);

// Level-3 ---------------------------------------------------------------------
//veblasStatus_t	veblasCgemm3m				(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
//veblasStatus_t	veblasCgemm3mStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, long long int strideA, const veFloatComplex_t* B, int ldb, long long int strideB, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc, long long int strideC, int batchCount);
//veblasStatus_t	veblasCherkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const float* beta, veFloatComplex_t* C, int ldc);
//veblasStatus_t	veblasCsyrkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
//veblasStatus_t	veblasDsyrkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const double* alpha, const double* A, int lda, const double* B, int ldb, const double* beta, double* C, int ldc);
//veblasStatus_t	veblasHgemm					(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const __half* alpha, const __half* A, int lda, const __half* B, int ldb, const __half* beta, __half* C, int ldc);
//veblasStatus_t	veblasHgemmBatched			(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const __half* alpha, const __half* Aarray[], int lda, const __half* Barray[], int ldb, const __half* beta, __half* Carray[], int ldc, int batchCount);
//veblasStatus_t	veblasHgemmStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const __half* alpha, const __half* A, int lda, long long int strideA, const __half* B, int ldb, long long int strideB, const __half* beta, __half* C, int ldc, long long int strideC, int batchCount);
//veblasStatus_t	veblasSsyrkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc);
//veblasStatus_t	veblasZgemm3m				(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
//veblasStatus_t	veblasZherkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const double* beta, veDoubleComplex_t* C, int ldc);
//veblasStatus_t	veblasZsyrkx				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasCgemm					(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCgemmBatched			(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* Aarray[], int lda, const veFloatComplex_t* Barray[], int ldb, const veFloatComplex_t* beta, veFloatComplex_t* Carray[], int ldc, int batchCount);
veblasStatus_t	veblasCgemmStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, long long int strideA, const veFloatComplex_t* B, int ldb, long long int strideB, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc, long long int strideC, int batchCount);
veblasStatus_t	veblasChemm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCher2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const float* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCherk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const float* alpha, const veFloatComplex_t* A, int lda, const float* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCsymm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCsyr2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCsyrk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* beta, veFloatComplex_t* C, int ldc);
veblasStatus_t	veblasCtrmm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, const veFloatComplex_t* B, int ldb, veFloatComplex_t* C, int ldc)\;
veblasStatus_t	veblasCtrsm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veFloatComplex_t* alpha, const veFloatComplex_t* A, int lda, veFloatComplex_t* B, int ldb);
veblasStatus_t	veblasCtrsmBatched			(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veFloatComplex_t* alpha, veFloatComplex_t* A[], int lda, veFloatComplex_t* B[], int ldb, int batchCount);;
veblasStatus_t	veblasDgemm					(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const double* alpha, const double* A, int lda, const double* B, int ldb, const double* beta, double* C, int ldc);
veblasStatus_t	veblasDgemmBatched			(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const double* alpha, const double* Aarray[], int lda, const double* Barray[], int ldb, const double* beta, double* Carray[], int ldc, int batchCount);
veblasStatus_t	veblasDgemmStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const double* alpha, const double* A, int lda, long long int strideA, const double* B, int ldb, long long int strideB, const double* beta, double* C, int ldc, long long int strideC, int batchCount);
veblasStatus_t	veblasDsyr2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const double* alpha, const double* A, int lda, const double* B, int ldb, const double* beta, double* C, int ldc);
veblasStatus_t	veblasDsyrk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const double* alpha, const double* A, int lda, const double* beta, double* C, int ldc);
veblasStatus_t	veblasDtrmm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const double* alpha, const double* A, int lda, const double* B, int ldb, double* C, int ldc);
veblasStatus_t	veblasDtrsm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const double* alpha, const double* A, int lda, double* B, int ldb);
veblasStatus_t	veblasDtrsmBatched			(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const double* alpha, double* A[], int lda, double* B[], int ldb, int batchCount);;
veblasStatus_t	veblasSgemm					(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc);
veblasStatus_t	veblasSgemmBatched			(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const float* alpha, const float* Aarray[], int lda, const float* Barray[], int ldb, const float* beta, float* Carray[], int ldc, int batchCount);
veblasStatus_t	veblasSgemmStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const float* alpha, const float* A, int lda, long long int strideA, const float* B, int ldb, long long int strideB, const float* beta, float* C, int ldc, long long int strideC, int batchCount);
veblasStatus_t	veblasSsymm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc)veblasStatus_t veblasDsymm(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const double* alpha, const double* A, int lda, const double* B, int ldb, const double* beta, double* C, int ldc);
veblasStatus_t	veblasSsyr2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const float* alpha, const float* A, int lda, const float* B, int ldb, const float* beta, float* C, int ldc);
veblasStatus_t	veblasSsyrk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const float* alpha, const float* A, int lda, const float* beta, float* C, int ldc);
veblasStatus_t	veblasStrmm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const float* alpha, const float* A, int lda, const float* B, int ldb, float* C, int ldc);
veblasStatus_t	veblasStrsm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const float* alpha, const float* A, int lda, float* B, int ldb);
veblasStatus_t	veblasStrsmBatched			(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const float* alpha, float* A[], int lda, float* B[], int ldb, int batchCount);;
veblasStatus_t	veblasZgemm					(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZgemmBatched			(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* Aarray[], int lda, const veDoubleComplex_t* Barray[], int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* Carray[], int ldc, int batchCount);
veblasStatus_t	veblasZgemmStridedBatched	(veblasHandle_t handle, veblasOperation_t transa, veblasOperation_t transb, int m, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, long long int strideA, const veDoubleComplex_t* B, int ldb, long long int strideB, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc, long long int strideC, int batchCount);
veblasStatus_t	veblasZhemm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZher2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const double* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZherk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const double* alpha, const veDoubleComplex_t* A, int lda, const double* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZsymm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZsyr2k				(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZsyrk					(veblasHandle_t handle, veblasFillMode_t uplo, veblasOperation_t trans, int n, int k, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* beta, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZtrmm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, const veDoubleComplex_t* B, int ldb, veDoubleComplex_t* C, int ldc);
veblasStatus_t	veblasZtrsm					(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veDoubleComplex_t* alpha, const veDoubleComplex_t* A, int lda, veDoubleComplex_t* B, int ldb);
veblasStatus_t	veblasZtrsmBatched			(veblasHandle_t handle, veblasSideMode_t side, veblasFillMode_t uplo, veblasOperation_t trans, veblasDiagType_t diag, int m, int n, const veDoubleComplex_t* alpha, veDoubleComplex_t* A[], int lda, veDoubleComplex_t* B[], int ldb, int batchCount);

}