#pragma once

namespace veda {
	namespace internal {
//------------------------------------------------------------------------------
enum Kernel {
	VEDA_KERNEL_MEMSET_U8 = 0,
	VEDA_KERNEL_MEMSET_U16,
	VEDA_KERNEL_MEMSET_U32,
	VEDA_KERNEL_MEMSET_U64,
	VEDA_KERNEL_MEMSET_U128,
	VEDA_KERNEL_MEMSET_U8_2D,
	VEDA_KERNEL_MEMSET_U16_2D,
	VEDA_KERNEL_MEMSET_U32_2D,
	VEDA_KERNEL_MEMSET_U64_2D,
	VEDA_KERNEL_MEMSET_U128_2D,
	VEDA_KERNEL_MEMCPY_D2D,
	VEDA_KERNEL_MEM_PTR,
	VEDA_KERNEL_MEM_SIZE,
	VEDA_KERNEL_MEM_SWAP,
	VEDA_KERNEL_MEM_ASSIGN,
	VEDA_KERNEL_MEM_REMOVE,
	VEDA_KERNEL_RAW_MEMSET_U8,
	VEDA_KERNEL_RAW_MEMSET_U16,
	VEDA_KERNEL_RAW_MEMSET_U32,
	VEDA_KERNEL_RAW_MEMSET_U64,
	VEDA_KERNEL_RAW_MEMSET_U128,
	VEDA_KERNEL_RAW_MEMSET_U8_2D,
	VEDA_KERNEL_RAW_MEMSET_U16_2D,
	VEDA_KERNEL_RAW_MEMSET_U32_2D,
	VEDA_KERNEL_RAW_MEMSET_U64_2D,
	VEDA_KERNEL_RAW_MEMSET_U128_2D,
	VEDA_KERNEL_RAW_MEMCPY_D2D,
	VEDA_KERNEL_CNT
};

//------------------------------------------------------------------------------
	}
}