IF(NOT NLC_FOUND)
	FILE(GLOB NLC_PATHS "/opt/nec/ve/nlc/*")
	LIST(SORT NLC_PATHS)
	LIST(LENGTH NLC_PATHS NLC_LEN)

	SET(NLC_PATH)
	SET(NLC_VERSION)
	SET(NLC_FOUND FALSE)

	IF(NLC_LEN GREATER 0)
		LIST(REVERSE NLC_PATHS)
		LIST(GET NLC_PATHS 0 NLC_PATH)
		STRING(REGEX MATCH "[0-9]+.[0-9]+.[0-9]+" NLC_VERSION ${NLC_PATH})
		MESSAGE(STATUS "Found NLC ${NLC_VERSION}")

		SET(NLC_PATH ${NLC_PATH})
		SET(NLC_VERSION ${NLC_VERSION})
		SET(NLC_FOUND TRUE)
	ELSEIF(${NLC_FIND_REQUIRED})
		MESSAGE(FATAL_ERROR "Unable to detect NEC NLC")
	ENDIF()

	SET(NLC_FOUND ${NLC_FOUND} CACHE BOOL "")
	SET(NLC_PATH ${NLC_PATH} CACHE PATH "")
	SET(NLC_VERSION ${NLC_VERSION} CACHE STRING "")

	MARK_AS_ADVANCED(NLC_FOUND NLC_PATH NLC_VERSION)

	UNSET(NLC_LEN)
	UNSET(NLC_PATHS)
ENDIF()